name: Continuous Deployment
on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: "master"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to Master
        if: ${{ success() && github.ref == 'refs/heads/develop' }}
        run: |
          git checkout origin/master
          git merge develop --no-ff --no-edit
          git push origin origin/master


